/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 1 "cilcode.tmp/ex20.c"
int main(void) 
{ 
  int x ;
  int y ;
  int z ;

  {
#line 1
  x = 5;
#line 1
  y = x;
#line 2
  x ++;
  L: 
#line 2
  y -= x;
#line 2
  z = y;
#line 3
  goto L;
#line 3
  return (0);
}
}
