/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 7 "cilcode.tmp/ex22.c"
int main(void) 
{ 


  {
#line 9
  printf((char const   * __restrict  )"Hello world\n");
#line 10
  return (0);
}
}
