/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 1 "cilcode.tmp/ex43.c"
int main(void) 
{ 
  int tmp ;

  {
#line 1
  goto L;
#line 1
  if (0) {
    L: 
#line 1
    tmp = 1;
  } else {
#line 1
    tmp = 0;
  }
#line 1
  return (tmp);
}
}
