/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 2 "cilcode.tmp/ex8.c"
struct foo {
   int x ;
   int y ;
};
#line 1 "cilcode.tmp/ex8.c"
int a1[5]  = {      1,      2,      3};
#line 2 "cilcode.tmp/ex8.c"
struct foo s1  =    {4, 0};
