/* Generated by CIL */

# 287 "/home/weimer/cil/lib/fixup.h"
union ioctl_format {
   int anInt ;
   int * __NODE(1)   anIntPtr ;
};
# 287
union ioctl_format ;
# 322
typedef void (* __NODE(2)   _box_sig_fn)(int  );
# 141
/* #pragma boxvararg_printf("printf",1) */
# 142
/* #pragma boxvararg_printf("vprintf",1) */
# 143
/* #pragma boxvararg_printf("fprintf",2) */
# 148
/* #pragma boxpoly("__startof") */
# 150
/* #pragma boxpoly("__endof") */
# 151
extern void * __endof(void *  ) ;
# 152
/* #pragma boxpoly("ccured_kind_of") */
# 153
extern char * ccured_kind_of(void *  ) ;
# 154
/* #pragma boxalloc("malloc",nozero,sizein(1)) */
# 155
/* #pragma boxpoly("free") */
# 156
/* #pragma boxalloc("alloca",nozero,sizein(1)) */
# 157
/* #pragma boxalloc("calloc",zero,sizemul(1,2)) */
# 165
/* #pragma boxalloc("__builtin_alloca",nozero,sizein(1)) */
# 171
static char * __NODE(3)   strchr_model(char * __NODE(4)   dest  __NODE(6)  ,
                                       int c )  __NODE(5)  ;
# 171
__inline static char * __NODE(3)   strchr_model(char * __NODE(4)   dest  __NODE(6)  ,
                                                int c ) 
{ 

  {
# 174
  return (dest);
}
}
# 176
/* #pragma cilnoremove("strchr_model") */
# 177
/* #pragma boxmodelof("strchr_model","strchr") */
extern void * __NODE(12)   /*0*/__endof(void * __NODE(13)    )  __NODE(14)  ;
# 179
static char * __NODE(7)   strdup_model(char const   * __NODE(8)   s  __NODE(16)  )  __NODE(9)  ;
# 179
__inline static char * __NODE(7)   strdup_model(char const   * __NODE(8)   s  __NODE(16)  ) 
{ char * __NODE(10)   p  __NODE(11)  ;

  {
# 182
  /*0*/__endof((void * __NODE(15)   )s);
# 183
  return (p);
}
}
# 185
/* #pragma cilnoremove("strdup_model") */
# 186
/* #pragma boxmodelof("strdup_model","strdup") */
extern void * __NODE(21)   /*1*/__endof(void * __NODE(22)    )  __NODE(23)  ;
extern void * __NODE(26)   /*2*/__endof(void * __NODE(27)    )  __NODE(28)  ;
# 189
static char * __NODE(17)   strpbrk_model(char const   * __NODE(18)   s  __NODE(25)  ,
                                         char const   * __NODE(19)   accept  __NODE(30)  )  __NODE(20)  ;
# 189
__inline static char * __NODE(17)   strpbrk_model(char const   * __NODE(18)   s  __NODE(25)  ,
                                                  char const   * __NODE(19)   accept  __NODE(30)  ) 
{ 

  {
# 191
  /*1*/__endof((void * __NODE(24)   )s);
# 192
  /*2*/__endof((void * __NODE(29)   )accept);
# 193
  return ((char * __NODE(31)   )s);
}
}
# 195
/* #pragma cilnoremove("strpbrk_model") */
# 196
/* #pragma boxmodelof("strpbrk_model","strpbrk") */
extern void * __NODE(36)   /*3*/__endof(void * __NODE(37)    )  __NODE(38)  ;
extern void * __NODE(41)   /*4*/__endof(void * __NODE(42)    )  __NODE(43)  ;
# 198
static char * __NODE(32)   strtok_model(char * __NODE(33)   s  __NODE(40)  ,
                                        char const   * __NODE(34)   delim  __NODE(45)  )  __NODE(35)  ;
# 198
__inline static char * __NODE(32)   strtok_model(char * __NODE(33)   s  __NODE(40)  ,
                                                 char const   * __NODE(34)   delim  __NODE(45)  ) 
{ 

  {
# 200
  /*3*/__endof((void * __NODE(39)   )s);
# 201
  /*4*/__endof((void * __NODE(44)   )delim);
# 202
  return (s);
}
}
# 204
/* #pragma cilnoremove("strtok_model") */
# 205
/* #pragma boxmodelof("strtok_model","strtok") */
# 207
/* #pragma boxpoly("memcpy") */
# 208
/* #pragma boxpoly("memset","__builtin_memset") */
# 209
/* #pragma boxpoly("memmove") */
# 210
/* #pragma boxpoly("memcmp") */
# 211
/* #pragma boxpoly("write") */
# 212
/* #pragma boxpoly("read") */
# 213
/* #pragma boxpoly("fread") */
# 214
/* #pragma boxpoly("fwrite") */
# 215
/* #pragma boxpoly("mmap") */
# 216
/* #pragma boxpoly("munmap") */
# 217
/* #pragma boxpoly("bzero") */
# 219
/* #pragma boxpoly("memset_seq_model") */
// Body of memset_seq_model used to be here

# 226
/* #pragma boxmodelof("memset_seq_model","memset","__builtin_memset") */
# 227
/* #pragma cilnoremove("memset_seq_model") */
# 231
/* #pragma boxpoly("memcpy_seq_model") */
// Body of memcpy_seq_model used to be here

# 239
/* #pragma boxmodelof("memcpy_seq_model","memcpy","memmove","__builtin_memcpy") */
# 241
/* #pragma cilnoremove("memcpy_seq_model") */
# 247
/* #pragma boxpoly("__builtin_memcpy") */
extern void * __NODE(55)   /*5*/__endof(void * __NODE(56)    )  __NODE(57)  ;
# 251
static void qsort_seq_model(void * __NODE(46)   base  __NODE(58)  ,
                            unsigned int nmemb , unsigned int size ,
                            int (* __NODE(49)   compar)(void const   * __NODE(47)    ,
                                                        void const   * __NODE(48)    )  __NODE(59)  )  __NODE(50)  ;
# 251
__inline static void qsort_seq_model(void * __NODE(46)   base  __NODE(58)  ,
                                     unsigned int nmemb , unsigned int size ,
                                     int (* __NODE(49)   compar)(void const   * __NODE(47)    ,
                                                                 void const   * __NODE(48)    )  __NODE(59)  ) 
{ void * __NODE(51)   end  __NODE(52)  ;
  void * __NODE(53)   tmp  __NODE(54)  ;

  {
# 255
  tmp = (void * __NODE(53)   )/*5*/__endof(base);
# 255
  end = tmp;
# 259
  ((*compar))((void const   * __NODE(60)   )base,
              (void const   * __NODE(61)   )base);
# 260
  return;
}
}
# 262
/* #pragma boxpoly("qsort") */
# 263
/* #pragma boxmodelof("qsort_seq_model","qsort") */
# 264
/* #pragma cilnoremove("qsort_seq_model") */
# 283
/* #pragma boxexported("main") */
# 291
/* #pragma boxvararg("ioctl",sizeof(union ioctl_format )) */
extern void * __NODE(66)   /*6*/__endof(void * __NODE(67)    )  __NODE(68)  ;
extern void * __NODE(71)   /*7*/__endof(void * __NODE(72)    )  __NODE(73)  ;
# 294
static int execv_model(char * __NODE(62)   path  __NODE(70)  ,
                       char * __NODE(63)   * __NODE(64)   argv  __NODE(75)  )  __NODE(65)  ;
# 294
__inline static int execv_model(char * __NODE(62)   path  __NODE(70)  ,
                                char * __NODE(63)   * __NODE(64)   argv  __NODE(75)  ) 
{ 

  {
# 297
  /*6*/__endof((void * __NODE(69)   )path);
# 298
  /*7*/__endof((void * __NODE(74)   )argv);
# 299
  return (0);
}
}
# 301
/* #pragma boxmodelof("execv_model","execv") */
extern void * __NODE(80)   /*8*/__endof(void * __NODE(81)    )  __NODE(82)  ;
# 305
static int getopt_model(int argc ,
                        char * __NODE(76)   * __NODE(77)   argv  __NODE(84)  ,
                        char const   * __NODE(78)   optstring )  __NODE(79)  ;
# 305
__inline static int getopt_model(int argc ,
                                 char * __NODE(76)   * __NODE(77)   argv  __NODE(84)  ,
                                 char const   * __NODE(78)   optstring ) 
{ 

  {
# 308
  /*8*/__endof((void * __NODE(83)   )argv);
# 309
  return (0);
}
}
# 311
/* #pragma boxmodelof("getopt_model","getopt") */
# 323
static void (* __NODE(85)   signal_model(int signum ,
                                         void (* __NODE(86)   fn)(int  )  __NODE(88)  ))(int  )  __NODE(87)  ;
# 323
__inline static void (* __NODE(85)   signal_model(int signum ,
                                                  void (* __NODE(86)   fn)(int  )  __NODE(88)  ))(int  ) 
{ 

  {
# 327
  return (fn);
}
}
# 329
/* #pragma cilnoremove("signal_model") */
# 330
/* #pragma boxmodelof("signal_model","signal") */
# 2 "testkinds.h"
extern int strcmp(char const   * __NODE(89)    , char const   * __NODE(90)    )  __NODE(91)  ;
# 5
int * __NODE(115)   safe  __NODE(116)   ;
# 6
int * __NODE(93)   wild  __NODE(94)   ;
# 7
int * __NODE(96)   fseq  __NODE(97)   ;
# 8
int * __NODE(98)   seq  __NODE(99)   ;
# 11
void setkinds(void)  __NODE(92)  ;
# 11
void setkinds(void) 
{ 

  {
# 12
  wild = (int * __NODE(95)   )(& wild);
# 13
  fseq = fseq + 1;
# 14
  seq = seq - 2;
# 14
  return;
}
}
# 1 "testharness.h"
extern int (__BOXFORMAT(1)  __BOXVARARG(union printf_format_union )   printf)(char const   * __NODE(100)    
                                                                              , ...)  __NODE(101)  ;
extern char * __NODE(117)   /*9*/ccured_kind_of(void * __NODE(118)    )  __NODE(119)  ;
# 10 "ptr1.c"
extern int __ccured_va_count  __NODE(124)  ;
# 10
extern int __ccured_va_tags[32] ;
# 4
int main(void)  __NODE(102)  ;
# 4
int main(void) 
{ int * __NODE(103)   * __NODE(104)   z  __NODE(105)  ;
  char * __NODE(106)   tmp  __NODE(107)  ;
  char const   * __NODE(108)   tmp_0  __NODE(109)  ;
  int tmp_1  __NODE(110)  ;

  {
# 7
  z = (int * __NODE(111)   * __NODE(112)   )(& z);
# 10
  if (sizeof(wild) == sizeof(safe)) {
# 10
    tmp = (char * __NODE(114)   )"WILD";
  } else {
# 10
    tmp = (char * __NODE(113)   )"WILD";
  }
# 10
  tmp_0 = (char const   * __NODE(108)   )/*9*/ccured_kind_of((void * __NODE(120)   )z);
# 10
  tmp_1 = strcmp(tmp_0, (char const   * __NODE(121)   )tmp);
# 10
  if (tmp_1) {
# 10
    __ccured_va_count = -1;
# 10
    printf((char const   * __NODE(122)   )((char * __NODE(123)   )"Error %d\n"),
           1);
# 10
    return (1);
  }
# 13
  __ccured_va_count = -1;
# 13
  printf((char const   * __NODE(125)   )((char * __NODE(126)   )"Success\n"));
# 13
  return (0);
}
}
#if 0
/* Now the graph */
/* Now the solved graph (simplesolve) */
0 : Glob(@dummy).0 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=
1 : Field(anIntPtr).0 () ()
 K=SAFE/unconstrained T=int 
  S=
  P=
2 : Type(_box_sig_fn).0 () ()
 K=SAFE/unconstrained T=void (int  )
  S=
  P=
3 : Static(./ptr1.i.strchr_model).1 () ()
 K=SAFE/unconstrained T=char 
  S=
  P=4:Cast
4 : Static(./ptr1.i.strchr_model).2 (escape,) ()
 K=SAFE/unconstrained T=char 
  S=3:Cast
  P=
5 : Static(./ptr1.i.strchr_model).0 () (4, 3)
 K=SAFE/unconstrained T=char * __NODE(3)   (char * __NODE(4)   dest  __NODE(6)  ,
                                            int c )
  S=
  P=
6 : Local(./ptr1.i.strchr_model.dest).0 (stack,) (4)
 K=SAFE/unconstrained T=char * __NODE(4)   
  S=
  P=
7 : Static(./ptr1.i.strdup_model).1 () ()
 K=SAFE/unconstrained T=char 
  S=
  P=10:Cast
8 : Static(./ptr1.i.strdup_model).2 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=char const   
  S=13:Cast, 15:Cast
  P=
9 : Static(./ptr1.i.strdup_model).0 () (8, 7)
 K=SAFE/unconstrained T=char * __NODE(7)   (char const   * __NODE(8)   s  __NODE(16)  )
  S=
  P=
10 : Local(./ptr1.i.strdup_model.p).1 (escape,) ()
 K=SAFE/unconstrained T=char 
  S=7:Cast
  P=
11 : Local(./ptr1.i.strdup_model.p).0 (stack,) (10)
 K=SAFE/unconstrained T=char * __NODE(10)   
  S=
  P=
12 : Glob(/*0*/__endof).1 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=
13 : Glob(/*0*/__endof).2 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=8:Cast, 15:Cast(0)
14 : Glob(/*0*/__endof).0 () (13, 12)
 K=SAFE/unconstrained T=void * __NODE(12)   (void * __NODE(13)    )
  S=
  P=
15 : Anon(0).0 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=void 
  S=13:Cast(0)
  P=8:Cast
16 : Local(./ptr1.i.strdup_model.s).0 (stack,) (8)
 K=SAFE/unconstrained T=char const   * __NODE(8)   
  S=
  P=
17 : Static(./ptr1.i.strpbrk_model).1 () ()
 K=SAFE/unconstrained T=char 
  S=
  P=31:Cast
18 : Static(./ptr1.i.strpbrk_model).2 (escape,posarith,reach_q,) ()
 K=FSEQ/from_flag T=char const   
  S=22:Cast, 31:Cast, 24:Cast
  P=
19 : Static(./ptr1.i.strpbrk_model).3 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=char const   
  S=27:Cast, 29:Cast
  P=
20 : Static(./ptr1.i.strpbrk_model).0 () (19, 18, 17)
 K=SAFE/unconstrained T=char * __NODE(17)   (char const   * __NODE(18)   s  __NODE(25)  ,
                                             char const   * __NODE(19)   accept  __NODE(30)  )
  S=
  P=
21 : Glob(/*1*/__endof).1 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=
22 : Glob(/*1*/__endof).2 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=18:Cast, 24:Cast(1)
23 : Glob(/*1*/__endof).0 () (22, 21)
 K=SAFE/unconstrained T=void * __NODE(21)   (void * __NODE(22)    )
  S=
  P=
24 : Anon(1).0 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=void 
  S=22:Cast(1)
  P=18:Cast
25 : Local(./ptr1.i.strpbrk_model.s).0 (stack,) (18)
 K=SAFE/unconstrained T=char const   * __NODE(18)   
  S=
  P=
26 : Glob(/*2*/__endof).1 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=
27 : Glob(/*2*/__endof).2 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=19:Cast, 29:Cast(2)
28 : Glob(/*2*/__endof).0 () (27, 26)
 K=SAFE/unconstrained T=void * __NODE(26)   (void * __NODE(27)    )
  S=
  P=
29 : Anon(2).0 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=void 
  S=27:Cast(2)
  P=19:Cast
30 : Local(./ptr1.i.strpbrk_model.accept).0 (stack,) (19)
 K=SAFE/unconstrained T=char const   * __NODE(19)   
  S=
  P=
31 : Anon(3).0 () ()
 K=SAFE/unconstrained T=char 
  S=17:Cast
  P=18:Cast
32 : Static(./ptr1.i.strtok_model).1 () ()
 K=SAFE/unconstrained T=char 
  S=
  P=33:Cast
33 : Static(./ptr1.i.strtok_model).2 (escape,posarith,reach_q,) ()
 K=FSEQ/from_flag T=char 
  S=37:Cast, 32:Cast, 39:Cast
  P=
34 : Static(./ptr1.i.strtok_model).3 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=char const   
  S=42:Cast, 44:Cast
  P=
35 : Static(./ptr1.i.strtok_model).0 () (34, 33, 32)
 K=SAFE/unconstrained T=char * __NODE(32)   (char * __NODE(33)   s  __NODE(40)  ,
                                             char const   * __NODE(34)   delim  __NODE(45)  )
  S=
  P=
36 : Glob(/*3*/__endof).1 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=
37 : Glob(/*3*/__endof).2 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=33:Cast, 39:Cast(3)
38 : Glob(/*3*/__endof).0 () (37, 36)
 K=SAFE/unconstrained T=void * __NODE(36)   (void * __NODE(37)    )
  S=
  P=
39 : Anon(4).0 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=void 
  S=37:Cast(3)
  P=33:Cast
40 : Local(./ptr1.i.strtok_model.s).0 (stack,) (33)
 K=SAFE/unconstrained T=char * __NODE(33)   
  S=
  P=
41 : Glob(/*4*/__endof).1 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=
42 : Glob(/*4*/__endof).2 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=34:Cast, 44:Cast(4)
43 : Glob(/*4*/__endof).0 () (42, 41)
 K=SAFE/unconstrained T=void * __NODE(41)   (void * __NODE(42)    )
  S=
  P=
44 : Anon(5).0 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=void 
  S=42:Cast(4)
  P=34:Cast
45 : Local(./ptr1.i.strtok_model.delim).0 (stack,) (34)
 K=SAFE/unconstrained T=char const   * __NODE(34)   
  S=
  P=
46 : Static(./ptr1.i.qsort_seq_model).1 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=void 
  S=48:Cast, 47:Cast, 61:Cast, 60:Cast, 56:Cast(5)
  P=
47 : Static(./ptr1.i.qsort_seq_model).3 () ()
 K=SAFE/unconstrained T=void const   
  S=
  P=46:Cast, 60:Cast(6)
48 : Static(./ptr1.i.qsort_seq_model).4 () ()
 K=SAFE/unconstrained T=void const   
  S=
  P=46:Cast, 61:Cast(6)
49 : Static(./ptr1.i.qsort_seq_model).2 () (48, 47)
 K=SAFE/unconstrained T=int (void const   * __NODE(47)    ,
                             void const   * __NODE(48)    )
  S=
  P=
50 : Static(./ptr1.i.qsort_seq_model).0 () (49, 46)
 K=SAFE/unconstrained T=void (void * __NODE(46)   base  __NODE(58)  ,
                              unsigned int nmemb , unsigned int size ,
                              int (* __NODE(49)   compar)(void const   * __NODE(47)    ,
                                                          void const   * __NODE(48)    )  __NODE(59)  )
  S=
  P=
51 : Local(./ptr1.i.qsort_seq_model.end).1 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=55:Cast, 53:Cast
52 : Local(./ptr1.i.qsort_seq_model.end).0 (stack,) (51)
 K=SAFE/unconstrained T=void * __NODE(51)   
  S=
  P=
53 : Local(./ptr1.i.qsort_seq_model.tmp).1 () ()
 K=SAFE/unconstrained T=void 
  S=51:Cast
  P=55:Cast(5)
54 : Local(./ptr1.i.qsort_seq_model.tmp).0 (stack,) (53)
 K=SAFE/unconstrained T=void * __NODE(53)   
  S=
  P=
55 : Glob(/*5*/__endof).1 () ()
 K=SAFE/unconstrained T=void 
  S=51:Cast, 53:Cast(5)
  P=
56 : Glob(/*5*/__endof).2 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=46:Cast(5)
57 : Glob(/*5*/__endof).0 () (56, 55)
 K=SAFE/unconstrained T=void * __NODE(55)   (void * __NODE(56)    )
  S=
  P=
58 : Local(./ptr1.i.qsort_seq_model.base).0 (stack,) (46)
 K=SAFE/unconstrained T=void * __NODE(46)   
  S=
  P=
59 : Local(./ptr1.i.qsort_seq_model.compar).0 (stack,) (49)
 K=SAFE/unconstrained T=int (* __NODE(49)   )(void const   * __NODE(47)    ,
                                              void const   * __NODE(48)    )
  S=
  P=
60 : Anon(6).0 () ()
 K=SAFE/unconstrained T=void const   
  S=47:Cast(6)
  P=46:Cast
61 : Anon(7).0 () ()
 K=SAFE/unconstrained T=void const   
  S=48:Cast(6)
  P=46:Cast
62 : Static(./ptr1.i.execv_model).1 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=char 
  S=67:Cast, 69:Cast
  P=
63 : Static(./ptr1.i.execv_model).3 () ()
 K=SAFE/unconstrained T=char 
  S=
  P=
64 : Static(./ptr1.i.execv_model).2 (posarith,reach_q,) (63)
 K=FSEQ/from_flag T=char * __NODE(63)   
  S=72:Cast, 74:Cast
  P=
65 : Static(./ptr1.i.execv_model).0 () (64, 62)
 K=SAFE/unconstrained T=int (char * __NODE(62)   path  __NODE(70)  ,
                             char * __NODE(63)   * __NODE(64)   argv  __NODE(75)  )
  S=
  P=
66 : Glob(/*6*/__endof).1 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=
67 : Glob(/*6*/__endof).2 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=62:Cast, 69:Cast(7)
68 : Glob(/*6*/__endof).0 () (67, 66)
 K=SAFE/unconstrained T=void * __NODE(66)   (void * __NODE(67)    )
  S=
  P=
69 : Anon(8).0 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=void 
  S=67:Cast(7)
  P=62:Cast
70 : Local(./ptr1.i.execv_model.path).0 (stack,) (62)
 K=SAFE/unconstrained T=char * __NODE(62)   
  S=
  P=
71 : Glob(/*7*/__endof).1 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=
72 : Glob(/*7*/__endof).2 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=64:Cast, 74:Cast(8)
73 : Glob(/*7*/__endof).0 () (72, 71)
 K=SAFE/unconstrained T=void * __NODE(71)   (void * __NODE(72)    )
  S=
  P=
74 : Anon(9).0 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=void 
  S=72:Cast(8)
  P=64:Cast
75 : Local(./ptr1.i.execv_model.argv).0 (stack,) (64)
 K=SAFE/unconstrained T=char * __NODE(63)   * __NODE(64)   
  S=
  P=
76 : Static(./ptr1.i.getopt_model).2 () ()
 K=SAFE/unconstrained T=char 
  S=
  P=
77 : Static(./ptr1.i.getopt_model).1 (posarith,reach_q,) (76)
 K=FSEQ/from_flag T=char * __NODE(76)   
  S=81:Cast, 83:Cast
  P=
78 : Static(./ptr1.i.getopt_model).3 () ()
 K=SAFE/unconstrained T=char const   
  S=
  P=
79 : Static(./ptr1.i.getopt_model).0 () (78, 77)
 K=SAFE/unconstrained T=int (int argc ,
                             char * __NODE(76)   * __NODE(77)   argv  __NODE(84)  ,
                             char const   * __NODE(78)   optstring )
  S=
  P=
80 : Glob(/*8*/__endof).1 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=
81 : Glob(/*8*/__endof).2 () ()
 K=SAFE/unconstrained T=void 
  S=
  P=77:Cast, 83:Cast(9)
82 : Glob(/*8*/__endof).0 () (81, 80)
 K=SAFE/unconstrained T=void * __NODE(80)   (void * __NODE(81)    )
  S=
  P=
83 : Anon(10).0 (posarith,reach_q,) ()
 K=FSEQ/from_flag T=void 
  S=81:Cast(9)
  P=77:Cast
84 : Local(./ptr1.i.getopt_model.argv).0 (stack,) (77)
 K=SAFE/unconstrained T=char * __NODE(76)   * __NODE(77)   
  S=
  P=
85 : Static(./ptr1.i.signal_model).1 () ()
 K=SAFE/unconstrained T=void (int  )
  S=
  P=86:Cast
86 : Static(./ptr1.i.signal_model).2 (escape,) ()
 K=SAFE/unconstrained T=void (int  )
  S=85:Cast
  P=
87 : Static(./ptr1.i.signal_model).0 () (86, 85)
 K=SAFE/unconstrained T=void (* __NODE(85)   (int signum ,
                                              void (* __NODE(86)   fn)(int  )  __NODE(88)  ))(int  )
  S=
  P=
88 : Local(./ptr1.i.signal_model.fn).0 (stack,) (86)
 K=SAFE/unconstrained T=void (* __NODE(86)   )(int  )
  S=
  P=
89 : Glob(strcmp).1 (interf,) ()
 K=SAFE/unconstrained T=char const   
  S=
  P=108:Cast(11)
90 : Glob(strcmp).2 (interf,) ()
 K=SAFE/unconstrained T=char const   
  S=
  P=121:Cast(11)
91 : Glob(strcmp).0 () (90, 89)
 K=SAFE/unconstrained T=int (char const   * __NODE(89)    ,
                             char const   * __NODE(90)    )
  S=
  P=
92 : Glob(setkinds).0 () ()
 K=SAFE/unconstrained T=void (void)
  S=
  P=
93 : Glob(wild).1 () ()
 K=WILD/cast(int (95) <= int * __NODE(93)   (94)) at testkinds.h:12 T=int 
  S=
  P=95:Cast
94 : Glob(wild).0 (escape,) (93)
 K=WILD/cast(int (95) <= int * __NODE(93)   (94)) at testkinds.h:12 T=int * __NODE(93)   
  S=95:Cast
  P=
95 : Anon(11).0 () ()
 K=WILD/cast(int (95) <= int * __NODE(93)   (94)) at testkinds.h:12 T=int 
  S=93:Cast
  P=94:Cast
96 : Glob(fseq).1 (escape,posarith,) ()
 K=FSEQ/from_flag T=int 
  S=96:Cast
  P=96:Cast
97 : Glob(fseq).0 () (96)
 K=SAFE/unconstrained T=int * __NODE(96)   
  S=
  P=
98 : Glob(seq).1 (escape,arith,) ()
 K=SEQ/from_flag T=int 
  S=98:Cast
  P=98:Cast
99 : Glob(seq).0 () (98)
 K=SAFE/unconstrained T=int * __NODE(98)   
  S=
  P=
100 : Glob(printf).1 (interf,) ()
 K=SAFE/unconstrained T=char const   
  S=
  P=125:Cast(13), 122:Cast(12)
101 : Glob(printf).0 () (100)
 K=SAFE/unconstrained T=int /*(__BOXFORMAT(1)  __BOXVARARG(union printf_format_union )   )*/(char const   * __NODE(100)    
                                                                                             , ...)
  S=
  P=
102 : Glob(main).0 () ()
 K=SAFE/unconstrained T=int (void)
  S=
  P=
103 : Local(./ptr1.i.main.z).2 (stack,) ()
 K=WILD/cast(int * __NODE(103)   (104) <= int (111)) at ptr1.c:13 T=int 
  S=111:Compat
  P=
104 : Local(./ptr1.i.main.z).1 (stack,) (103)
 K=WILD/cast(int * __NODE(103)   (104) <= int (111)) at ptr1.c:13 T=int * __NODE(103)   
  S=118:Cast, 120:Cast
  P=111:Compat, 112:Cast
105 : Local(./ptr1.i.main.z).0 (stack,) (104)
 K=WILD/spread_from_edge(112) T=int * __NODE(103)   * __NODE(104)   
  S=112:Cast
  P=
106 : Local(./ptr1.i.main.tmp).1 () ()
 K=SAFE/unconstrained T=char 
  S=121:Cast
  P=114:Cast, 113:Cast
107 : Local(./ptr1.i.main.tmp).0 (stack,) (106)
 K=SAFE/unconstrained T=char * __NODE(106)   
  S=
  P=
108 : Local(./ptr1.i.main.tmp_0).1 () ()
 K=SAFE/unconstrained T=char const   
  S=89:Cast(11)
  P=117:Cast(10)
109 : Local(./ptr1.i.main.tmp_0).0 (stack,) (108)
 K=SAFE/unconstrained T=char const   * __NODE(108)   
  S=
  P=
110 : Local(./ptr1.i.main.tmp_1).0 (stack,) ()
 K=SAFE/unconstrained T=int 
  S=
  P=
111 : Anon(12).1 (stack,) ()
 K=WILD/cast(int * __NODE(103)   (104) <= int (111)) at ptr1.c:13 T=int 
  S=104:Compat
  P=103:Compat
112 : Anon(12).0 (stack,) (111)
 K=WILD/spread_from_edge(104) T=int * __NODE(111)   
  S=104:Cast
  P=105:Cast
113 : Anon(13).0 () ()
 K=SAFE/unconstrained T=char 
  S=106:Cast
  P=
114 : Anon(14).0 () ()
 K=SAFE/unconstrained T=char 
  S=106:Cast
  P=
115 : Glob(safe).1 () ()
 K=SAFE/unconstrained T=int 
  S=
  P=
116 : Glob(safe).0 () (115)
 K=SAFE/unconstrained T=int * __NODE(115)   
  S=
  P=
117 : Glob(/*9*/ccured_kind_of).1 () ()
 K=SAFE/unconstrained T=char 
  S=108:Cast(10)
  P=
118 : Glob(/*9*/ccured_kind_of).2 (stack,) ()
 K=WILD/spread_from_edge(104) T=void 
  S=
  P=104:Cast, 120:Cast(10)
119 : Glob(/*9*/ccured_kind_of).0 () (118, 117)
 K=SAFE/unconstrained T=char * __NODE(117)   (void * __NODE(118)    )
  S=
  P=
120 : Anon(15).0 (stack,) ()
 K=WILD/spread_from_edge(104) T=void 
  S=118:Cast(10)
  P=104:Cast
121 : Anon(16).0 () ()
 K=SAFE/unconstrained T=char const   
  S=90:Cast(11)
  P=106:Cast
122 : Anon(17).0 () ()
 K=SAFE/unconstrained T=char const   
  S=100:Cast(12)
  P=123:Cast
123 : Anon(18).0 () ()
 K=SAFE/unconstrained T=char 
  S=122:Cast
  P=
124 : Glob(__ccured_va_count).0 () ()
 K=SAFE/unconstrained T=int 
  S=
  P=
125 : Anon(19).0 () ()
 K=SAFE/unconstrained T=char const   
  S=100:Cast(13)
  P=126:Cast
126 : Anon(20).0 () ()
 K=SAFE/unconstrained T=char 
  S=125:Cast
  P=
/* End of solved graph*/
#endif
