# Makefile in small2

clean:
	rm -f *.o *_all.c *cil.c *box.c *_ppp.c *.i *.origi *infer.c *cabs.c
	rm -f comb enuminit multiplestatics staticafternostorage
	rm -f hola partialbracket ptrtolocal rmunused recursetype
	rm -f regbeforeassign simplewild tprintf voidfree
	rm -f *.exe *.obj *.pdb *.ilk
	rm -f __scalar2pointer.txt ocamlprof.dump "#"*
	rm -f *cured.c *.optim.c *_comb.c
	rm -rf *.browser
