/*
 *
 * Copyright (c) 2001 by
 *  George C. Necula	necula@cs.berkeley.edu
 *  Scott McPeak        smcpeak@cs.berkeley.edu
 *  Wes Weimer          weimer@cs.berkeley.edu
 *   
 * All rights reserved.  Permission to use, copy, modify and distribute
 * this software for research purposes only is hereby granted, 
 * provided that the following conditions are met: 
 * 1. XSRedistributions of source code must retain the above copyright notice, 
 * this list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright notice, 
 * this list of conditions and the following disclaimer in the documentation 
 * and/or other materials provided with the distribution. 
 * 3. The name of the authors may not be used to endorse or promote products 
 * derived from  this software without specific prior written permission. 
 *
 * DISCLAIMER:
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR 
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS 
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON 
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF 
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <stdio.h>

#ifdef _GNUCC
#define LONGLONG long long
#endif

#ifdef _MSVC
#define LONGLONG __int64
#endif

int main() {
  fprintf(stderr, "Generating machine dependency information for CIL\n");

  printf("(* Generated by code in %s *)\n", __FILE__);
  // Size of certain types
  printf("\tlet sizeof_int       = %d\n", sizeof(int));
  printf("\tlet sizeof_short     = %d\n", sizeof(short));
  printf("\tlet sizeof_long      = %d\n", sizeof(long));
  printf("\tlet sizeof_longlong  = %d\n", sizeof(LONGLONG));
  printf("\tlet sizeof_ptr       = %d\n", sizeof(int *));
  printf("\tlet sizeof_enum      = %d\n", sizeof(enum { ONE, TWO }));
  printf("\tlet sizeof_longdouble  = %d\n", sizeof(long double));

  // The alignment of long long
  {
    struct longlong {
      char c;
      LONGLONG ll;
    };
    printf("\tlet alignof_longlong = %d\n",
           (int)(&((struct longlong*)0)->ll));
  }

  // The alignment of double
  {
    struct s1 {
      char c;
      double d;
    };
    printf("\tlet alignof_double = %d\n",
           (int)(&((struct s1*)0)->d));
  }    

  // The alignment of long  double
  {
    struct s1 {
      char c;
      long double ld;
    };
    printf("\tlet alignof_longdouble = %d\n",
           (int)(&((struct s1*)0)->ld));
  }    

  // The type of sizeof
  printf("\tlet ikind_sizeof_is_long = %s\n",
         sizeof(int) == sizeof(sizeof(long)) ? "true" : "false");

  // Whether char is unsigned
  printf("\tlet char_is_unsigned = %s\n", 
         ((char)0xff) > 0 ? "true" : "false");


  exit(0);
}
